name: rse-course
channels:
  - anaconda
dependencies:
  - python=3.8
  - jupyter
  - pip
  - pip:
    - numpy
    - scipy
    - matplotlib
    - ipython[all]
    - tornado
    - jinja2
    - pyzmq
    - pytest
    - jupyterlab